service: max-fun-api
provider:
  name: aws
  runtime: nodejs10.x
plugins:
  - serverless-webpack
custom:
  webpack:
    packager: yarn
    webpackConfig: ./webpack.config.js
    includeModules: true
functions:
  app:
    handler: main.graphqlHandler